### ISSUE TITLE
time-wrap doesn't match expected length

### ISSUE THREAD

**Issue by rsenft1** [rethomics/ggetho#46]
Hi, I recently started using ggetho with some mouse activity data and I noticed that the data does not extend as far as predicted when using `time-wrap`. For an example, see the [documentation](https://rethomics.github.io/sleepr.html): 
![image](https://user-images.githubusercontent.com/28116530/177069392-b7e45ee3-5000-468c-97c3-52703c591e27.png)
`time-wrap` is set to 24 hours, but the graph and annotations only span ~23.5 hrs. Why is this?

**Comment by qgeissmann** [comment]
Hi @rsenft1,
Thanks for your question. This is the expected behaviour. When you get a data point at 00:00, in your case, the point at 24:00 would be the exact same. For statistical reasons, we decided not to show the same data point twice (at 00:00 and 24:00) as we would arbitrarily over-represent the data at 0/24h. This also makes things more 'natural' for representing data in a polar coordinate system... If it makes sense, we can close this issue. Also happy to help if it is not the behaviour you want

**Comment by rsenft1** [comment]
Ah yes, that does make sense, especially when using polar coordinates. Thanks so much for the quick response!
